<?php

/**
 * Invitation Builder — animated themes, envelope, details, blocks (Wooow-style).
 * Add new animated themes to `animated_themes` (not legacy blade templates 1–21).
 */
return [

    'defaults' => [
        'event_category' => 'wedding',
        'theme_slug' => 'romantic-blush',
        'theme_template' => 16,
        'theme_mode' => 'dark',
        'opening_type' => 'envelope',
        'primary_color' => '#c9a962',
        'secondary_color' => '#e8b4b8',
        'background_color' => '#1a1520',
        'text_color' => '#faf6f0',
        'font_family' => 'Cairo',
        'headline_font' => 'Playfair Display',
        'animated_theme' => true,
        'music_enabled' => true,
        'welcome_enabled' => false,
        'envelope_color' => 'cream',
        'seal_style' => 'wax_classic',
        'envelope_initials' => '',
        'opening_headline' => '',
        'date_position' => 'center',
        'block_accent_color' => '#c9a962',
        'block_floral_border' => true,
        'blocks' => ['countdown', 'venue', 'rsvp'],
    ],

    'theme_categories' => [
        'romantic' => ['label_ar' => 'رومانسي', 'label_en' => 'Romantic'],
        'tropical' => ['label_ar' => 'استوائي', 'label_en' => 'Tropical'],
        'elegant' => ['label_ar' => 'أنيق', 'label_en' => 'Elegant'],
        'modern' => ['label_ar' => 'عصري', 'label_en' => 'Modern'],
        'fairytale' => ['label_ar' => 'خرافي', 'label_en' => 'Fairytale'],
        'minimal' => ['label_ar' => 'بسيط', 'label_en' => 'Minimal'],
    ],

    /**
     * Animated themes (add more here — shown in builder tab 1).
     * renderer_template: internal blade used until per-theme views exist.
     */
    'animated_themes' => [
        'romantic-blush' => [
            'name_ar' => 'رومانسي وردي',
            'name_en' => 'Romantic Blush',
            'category' => 'romantic',
            'preview' => 'linear-gradient(135deg, #f8e8ee 0%, #e8b4b8 50%, #c9a962 100%)',
            'primary_color' => '#c9a962',
            'secondary_color' => '#e8b4b8',
            'background_color' => '#2d1f28',
            'text_color' => '#faf6f0',
            'renderer_template' => 16,
        ],
        'tropical-paradise' => [
            'name_ar' => 'جنة استوائية',
            'name_en' => 'Tropical Paradise',
            'category' => 'tropical',
            'preview' => 'linear-gradient(135deg, #0d9488 0%, #34d399 40%, #fbbf24 100%)',
            'primary_color' => '#14b8a6',
            'secondary_color' => '#fbbf24',
            'background_color' => '#0f2922',
            'text_color' => '#ecfdf5',
            'renderer_template' => 16,
        ],
        'fairy-tale-castle' => [
            'name_ar' => 'قلعة خرافية',
            'name_en' => 'Fairy Tale Castle',
            'category' => 'fairytale',
            'preview' => 'linear-gradient(135deg, #a78bfa 0%, #c4b5fd 50%, #fce7f3 100%)',
            'primary_color' => '#a78bfa',
            'secondary_color' => '#fce7f3',
            'background_color' => '#1e1b4b',
            'text_color' => '#f5f3ff',
            'renderer_template' => 16,
        ],
        'elegant-minimal' => [
            'name_ar' => 'أناقة بسيطة',
            'name_en' => 'Elegant Minimal',
            'category' => 'minimal',
            'preview' => 'linear-gradient(135deg, #fafafa 0%, #e5e5e5 50%, #171717 100%)',
            'primary_color' => '#171717',
            'secondary_color' => '#737373',
            'background_color' => '#fafafa',
            'text_color' => '#171717',
            'renderer_template' => 16,
        ],
        'golden-gatsby' => [
            'name_ar' => 'ذهبي غاتسبي',
            'name_en' => 'Golden Gatsby',
            'category' => 'elegant',
            'preview' => 'linear-gradient(135deg, #1c1917 0%, #ca8a04 50%, #fde047 100%)',
            'primary_color' => '#ca8a04',
            'secondary_color' => '#fde047',
            'background_color' => '#1c1917',
            'text_color' => '#fef3c7',
            'renderer_template' => 16,
        ],
        'garden-party' => [
            'name_ar' => 'حفلة الحديقة',
            'name_en' => 'Garden Party',
            'category' => 'romantic',
            'preview' => 'linear-gradient(135deg, #86efac 0%, #fef08a 50%, #fda4af 100%)',
            'primary_color' => '#16a34a',
            'secondary_color' => '#fda4af',
            'background_color' => '#14532d',
            'text_color' => '#f0fdf4',
            'renderer_template' => 16,
        ],
        'ocean-breeze' => [
            'name_ar' => 'نسيم المحيط',
            'name_en' => 'Ocean Breeze',
            'category' => 'tropical',
            'preview' => 'linear-gradient(135deg, #0ea5e9 0%, #38bdf8 50%, #e0f2fe 100%)',
            'primary_color' => '#0284c7',
            'secondary_color' => '#7dd3fc',
            'background_color' => '#0c4a6e',
            'text_color' => '#f0f9ff',
            'renderer_template' => 16,
        ],
        'desert-sunset' => [
            'name_ar' => 'غروب الصحراء',
            'name_en' => 'Desert Sunset',
            'category' => 'tropical',
            'preview' => 'linear-gradient(135deg, #ea580c 0%, #f97316 50%, #fcd34d 100%)',
            'primary_color' => '#ea580c',
            'secondary_color' => '#fcd34d',
            'background_color' => '#431407',
            'text_color' => '#fff7ed',
            'renderer_template' => 16,
        ],
        'midnight-velvet' => [
            'name_ar' => 'مخمل ليلي',
            'name_en' => 'Midnight Velvet',
            'category' => 'elegant',
            'preview' => 'linear-gradient(135deg, #1e1b4b 0%, #4c1d95 50%, #c084fc 100%)',
            'primary_color' => '#7c3aed',
            'secondary_color' => '#c084fc',
            'background_color' => '#0f0a1a',
            'text_color' => '#ede9fe',
            'renderer_template' => 16,
        ],
        'cherry-blossom' => [
            'name_ar' => 'زهر الكرز',
            'name_en' => 'Cherry Blossom',
            'category' => 'romantic',
            'preview' => 'linear-gradient(135deg, #fce7f3 0%, #f9a8d4 50%, #fbcfe8 100%)',
            'primary_color' => '#db2777',
            'secondary_color' => '#fbcfe8',
            'background_color' => '#500724',
            'text_color' => '#fdf2f8',
            'renderer_template' => 16,
        ],
        'modern-geo' => [
            'name_ar' => 'هندسي عصري',
            'name_en' => 'Modern Geo',
            'category' => 'modern',
            'preview' => 'linear-gradient(135deg, #18181b 0%, #3f3f46 50%, #f43f5e 100%)',
            'primary_color' => '#f43f5e',
            'secondary_color' => '#a1a1aa',
            'background_color' => '#09090b',
            'text_color' => '#fafafa',
            'renderer_template' => 16,
        ],
        'lavender-fields' => [
            'name_ar' => 'حقول الخزامى',
            'name_en' => 'Lavender Fields',
            'category' => 'romantic',
            'preview' => 'linear-gradient(135deg, #c4b5fd 0%, #a78bfa 50%, #ede9fe 100%)',
            'primary_color' => '#7c3aed',
            'secondary_color' => '#ddd6fe',
            'background_color' => '#2e1065',
            'text_color' => '#f5f3ff',
            'renderer_template' => 16,
        ],
    ],

    'envelope_colors' => [
        'cream' => ['label_ar' => 'كريمي', 'hex' => '#f5f0e6', 'swatch' => '#f5f0e6'],
        'blush' => ['label_ar' => 'وردي فاتح', 'hex' => '#f4d4d4', 'swatch' => '#f4d4d4'],
        'navy' => ['label_ar' => 'كحلي', 'hex' => '#1e3a5f', 'swatch' => '#1e3a5f'],
        'sage' => ['label_ar' => 'أخضر زيتوني', 'hex' => '#9caf88', 'swatch' => '#9caf88'],
        'gold' => ['label_ar' => 'ذهبي', 'hex' => '#d4af37', 'swatch' => '#d4af37'],
        'blush_pink' => ['label_ar' => 'وردي بلاش', 'hex' => '#e8b4b8', 'swatch' => '#e8b4b8'],
        'ivory' => ['label_ar' => 'عاجي', 'hex' => '#fffff0', 'swatch' => '#fffff0'],
        'charcoal' => ['label_ar' => 'فحمي', 'hex' => '#36454f', 'swatch' => '#36454f'],
        'burgundy' => ['label_ar' => 'عنابي', 'hex' => '#722f37', 'swatch' => '#722f37'],
    ],

    'seal_styles' => [
        'wax_classic' => ['label_ar' => 'شمع كلاسيكي', 'label_en' => 'Classic Wax Seal', 'icon' => '🔴'],
        'floral_emboss' => ['label_ar' => 'نقش زهري', 'label_en' => 'Floral Emboss', 'icon' => '🌸'],
    ],

    'fonts' => [
        'Cairo' => 'Cairo',
        'Playfair Display' => 'Playfair Display',
        'Amiri' => 'Amiri',
        'Tajawal' => 'Tajawal',
        'Cormorant Garamond' => 'Cormorant Garamond',
        'Great Vibes' => 'Great Vibes',
        'Lora' => 'Lora',
        'Merriweather' => 'Merriweather',
        'Montserrat' => 'Montserrat',
        'Raleway' => 'Raleway',
        'Libre Baskerville' => 'Libre Baskerville',
        'Dancing Script' => 'Dancing Script',
        'Josefin Sans' => 'Josefin Sans',
        'Cormorant' => 'Cormorant',
        'EB Garamond' => 'EB Garamond',
        'Noto Naskh Arabic' => 'Noto Naskh Arabic',
    ],

    'date_positions' => [
        'top' => ['label_ar' => 'أعلى البطاقة', 'label_en' => 'Top'],
        'center' => ['label_ar' => 'وسط البطاقة', 'label_en' => 'Center'],
        'bottom' => ['label_ar' => 'أسفل البطاقة', 'label_en' => 'Bottom'],
    ],

    'information_blocks' => [
        'countdown' => ['label_ar' => 'عداد تنازلي', 'icon' => '⏱', 'description_ar' => 'العد التنازلي ليوم الحدث'],
        'venue' => ['label_ar' => 'المكان', 'icon' => '📍', 'description_ar' => 'عنوان القاعة والخريطة'],
        'timeline' => ['label_ar' => 'الجدول الزمني', 'icon' => '📅', 'description_ar' => 'برنامج اليوم'],
        'dress_code' => ['label_ar' => 'قواعد اللباس', 'icon' => '👗', 'description_ar' => 'الزي المطلوب'],
        'gift_list' => ['label_ar' => 'قائمة الهدايا', 'icon' => '🎁', 'description_ar' => 'سجل الهدايا أو التبرعات'],
        'our_story' => ['label_ar' => 'قصتنا', 'icon' => '💕', 'description_ar' => 'قصة العروسين'],
        'gallery' => ['label_ar' => 'معرض صور', 'icon' => '🖼', 'description_ar' => 'صور مميزة'],
        'rsvp' => ['label_ar' => 'تأكيد الحضور', 'icon' => '✉️', 'description_ar' => 'قبول أو رفض الدعوة'],
        'parking' => ['label_ar' => 'مواقف السيارات', 'icon' => '🚗', 'description_ar' => 'معلومات المواقف'],
        'accommodation' => ['label_ar' => 'الإقامة', 'icon' => '🏨', 'description_ar' => 'فنادق قريبة'],
        'faq' => ['label_ar' => 'أسئلة شائعة', 'icon' => '❓', 'description_ar' => 'إجابات للضيوف'],
        'contact' => ['label_ar' => 'تواصل', 'icon' => '📞', 'description_ar' => 'أرقام التواصل'],
        'menu' => ['label_ar' => 'قائمة الطعام', 'icon' => '🍽', 'description_ar' => 'أطباق الحفل'],
        'transport' => ['label_ar' => 'المواصلات', 'icon' => '🚌', 'description_ar' => 'باصات الضيوف'],
        'wishes' => ['label_ar' => 'تهاني', 'icon' => '💬', 'description_ar' => 'رسائل من الضيوف'],
    ],

    'event_types' => [
        'wedding' => ['label_ar' => 'زفاف', 'label_en' => 'Wedding', 'icon' => '💒'],
        'conference' => ['label_ar' => 'مؤتمر', 'label_en' => 'Conference', 'icon' => '🎤'],
        'seminar' => ['label_ar' => 'ندوة', 'label_en' => 'Seminar', 'icon' => '📚'],
        'medical_event' => ['label_ar' => 'فعالية طبية', 'label_en' => 'Medical Event', 'icon' => '🏥'],
        'business_meeting' => ['label_ar' => 'اجتماع عمل', 'label_en' => 'Business Meeting', 'icon' => '💼'],
        'product_launch' => ['label_ar' => 'إطلاق منتج', 'label_en' => 'Product Launch', 'icon' => '🚀'],
        'birthday' => ['label_ar' => 'عيد ميلاد', 'label_en' => 'Birthday', 'icon' => '🎂'],
        'graduation' => ['label_ar' => 'تخرج', 'label_en' => 'Graduation', 'icon' => '🎓'],
        'custom' => ['label_ar' => 'مناسبة مخصصة', 'label_en' => 'Custom Event', 'icon' => '✨'],
    ],

    'opening_types' => [
        'envelope' => ['label_ar' => 'ظرف متحرك', 'label_en' => 'Animated envelope'],
        'welcome' => ['label_ar' => 'شاشة ترحيب ثم الظرف', 'label_en' => 'Welcome screen + envelope'],
        'intro_video' => ['label_ar' => 'فيديو افتتاحي ثم الظرف', 'label_en' => 'Intro video + envelope'],
    ],

    'theme_modes' => [
        'dark' => ['label_ar' => 'داكن', 'label_en' => 'Dark'],
        'light' => ['label_ar' => 'فاتح', 'label_en' => 'Light'],
    ],

];
